[package]
name = "kanshi"
description = "Easy-to-use rust crate for watching the filesystem"
homepage = "https://github.com/carlvoller/kanshi"
repository = "https://github.com/carlvoller/kanshi"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
readme = "./README.md"

[dependencies]
async-stream = "0.3.6"
bitflags = "2.6.0"
futures = "0.3"
libc = "0.2.166"
once_cell = "1.20.3"
thiserror = "1.0.64"
tokio = { version = "1.41.1", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
tokio-util = "0.7.13"

[target.'cfg(unix)'.dependencies]
nix = { features = ["event", "fanotify", "fs", "inotify"], git = "https://github.com/carlvoller/nix", branch = "master" }

[target.'cfg(windows)'.dependencies]
windows-sys = "0.59.0"
